apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nishantabanik/kube-features.git
    targetRevision: main
    path: infrastructure/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
